### ISSUE TITLE
Erro ao executar "mvn install" após clonar repositório

### ISSUE THREAD

**Issue by klebermo** [mercadolibre/java-sdk#31]
1 error
6 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:32 min
[INFO] Finished at: 2020-02-05T13:34:13-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project swagger-java-client: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:96: warning: no @throws for io.swagger.client.ApiException
[ERROR]     public String getAuthUrl(String redirectUri, Configuration.AuthUrls authUrl) throws ApiException {
[ERROR]                   ^
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:131: warning: no @param for code
[ERROR]     public AccessToken authorize(String code, String redirectUri) throws ApiException {
[ERROR]                        ^
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:131: warning: no @param for redirectUri
[ERROR]     public AccessToken authorize(String code, String redirectUri) throws ApiException {
[ERROR]                        ^
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:131: warning: no @return
[ERROR]     public AccessToken authorize(String code, String redirectUri) throws ApiException {
[ERROR]                        ^
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:131: warning: no @throws for io.swagger.client.ApiException
[ERROR]     public AccessToken authorize(String code, String redirectUri) throws ApiException {
[ERROR]                        ^
[ERROR] C:\Users\00940831503\Desktop\java-sdk-master\src\main\java\io\swagger\client\api\DefaultApi.java:184: warning: no @param for refreshToken
[ERROR]     public RefreshToken refreshAccessToken(String refreshToken) throws ApiException {
[ERROR]                         ^
[ERROR]
[ERROR] Command line was: c:\Users\00940831503\Downloads\jdk-13.0.1\bin\javadoc.exe @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\00940831503\Desktop\java-sdk-master\target\apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by manasouza** [comment]
Está usando JDK 13? Caso afirmativo, tente mudar para o JDK referenciado no `maven-compiler-plugin`

**Comment by klebermo** [comment]
Consegui instalar com o JDK 13 mesmo, mas desativando os JavaDocs com a opção de linha de comando -Dmaven.javadoc.skip=true.
